In [11]:
from __future__ import print_function
import torch
import numpy as np

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU



In [12]:
#Create a randon tensor

#tensor size
m,n,t= 6,6,6
r=5
# create sparse tensor X with ones at idx 
idx = torch.LongTensor([[0, 1, 1],
                          [2, 0, 2],
                           [1,1,2]]) #idx for 
value = torch.ones(3)
X=torch.sparse.FloatTensor(idx, value, torch.Size([m,n,t])).to_dense()

In [18]:
#SVD 
def mat_svd(X,r):
    #Mode-1 folding
    X1= X.reshape(m,n*t)
    U,S,V= torch.svd(X1,some=True, compute_uv=True) 
    U1=U[:,:r]
    #Mode-2 folding
    X2= X.reshape(m*t,n) 
    U,S,V= torch.svd(X2,some=True, compute_uv=True) 
    V1=V[:,:r]
    return U1,V1
U1,V1= mat_svd(X,r)
U1,V1


(tensor([[0., 1., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.]]), tensor([[-0., -0.,  0.,  0.,  0.],
         [-1., -0.,  0.,  0.,  0.],
         [-0., -1.,  0.,  0.,  0.],
         [-0., -0.,  0.,  0.,  1.],
         [-0., -0.,  1.,  0.,  0.],
         [-0., -0.,  0.,  1.,  0.]]))

In [20]:
#Update S based on U1, V1
def update_s(U, X, V, r ):
    new_s = torch.empty((r,r,t))
    for i in range(t): 
        m1 = torch.mm(torch.t(U),X[i]) #torch.t = transpose
        m2 = torch.mm(m1,V)
        new_s[:,:,i]=m2
    return new_s

S=update_s(U1,X,V1,r)

In [21]:
#Compute Z:
def update_z(U,V,S):
    new_z = torch.empty((m,n,t))
    for i in range(t): 
        S_t=S[:,:,i]
        m1 = torch.mm(U,S_t)
        m2 = torch.mm(m1,torch.t(V))
        new_z[:,:,i]=m2
    return new_z
Z=update_z(U1,V1,S)



In [34]:
#wrap up everything 
def tensor_svd(Z0,r,T=50):
    #initialise Z
    Z1=Z0
    error=100
    for t in range(T):
        if error > 1: 
            print(t,)
            R=Z1
            U1,V1= mat_svd(R,r)
            S=update_s(U1,R,V1,r)
            Z1=update_z(U1,V1,S)
            error=(Z1-Z0).pow(2).sum().item()
    print('code stopped at t=%s at error=%s'%(t,error))
    return Z1    
            
tensor_svd(X,r)         

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
code stopped at t=49 at error=3.0


tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0.

(array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]], dtype=float32),
 array([1.4142135, 1.       , 0.       ], dtype=float32),
 array([[ 0.        ,  0.70710677,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.70710677],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.     

In [49]:
# useful website for operations: https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/
X_5= torch.cat((X,X,X), dim=2) # Concatenate X's in the 0 dimension

X.shape, X_5.shape

(torch.Size([6, 6, 6]), torch.Size([6, 6, 18]))